title: Datatähti
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datatahti.fi" # the base hostname & protocol for your site, e.g. http://example.com
year: 2025

permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
